### ISSUE TITLE
Check the correctness of COMET internal mapping

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/COMET-DCB-Mapping#3]
@manuelfs I have release a debug mapping (see [1]) for COMET FPGA (`IC3`) -> COMET `J1`. Please help me check the correctness of the mapping (maybe with the help of some undergrads).

It might be useful to refer to the wiki (see [2]) to see some workarounds that I implemented.

It is also worth noting that I rearranged the `J6` pins in the `comet_db.net` so that they are ordered logically. (See umd-lhcb/lab-notes#16, umd-lhcb/lab-notes#17 for details).

[1]: https://github.com/umd-lhcb/COMET-DCB-mapping/releases/tag/0.2.1
[2]: https://github.com/umd-lhcb/COMET-DCB-mapping/wiki

**Comment by yipengsun** [comment]
`v0.2.1` has also include `J2` in COMET internal mapping. Please use the newer release to check connections.

**Comment by yipengsun** [comment]
The process of from COMET `J6`, then to COMET DB `J6`, then going back to COMET `J6` is very hand-wavy. They seem to agree with manual tracing, but I can't explain line 354:
```
        another_comet_pin = ('J6', str(int(comet_db_pin[1])+1))
```
Previously I assumed COMET `JD6, pin x` <-> COMET DB `JD6, pin x+1`. Here we are converting a COMET DB pin to a COMET pin, so it makes sense to _subtract_ 1, instead of _add_ 1.

**Comment by yipengsun** [comment]
Actually, `+1` does make sense:

* Right COMET `JD6, pin x` <-> Right COMET DB `JD6, pin x+1`
* Left COMET DB `JD6, pin x` <-> Left COMET `JD6, pin x+1`

This is because on schematic, the connector is flipped horizontally. This would produce the 2 rules listed above.

**Comment by jorger99** [comment]
Firstly,
After lots of ~~arguing~~ discussion about even/odd/left/right, we have determined a rule for matching pins for J6:

**The even side of J6 on the COMET has Pin N corresponding to Pin N-1 on the DB’s J6. The odd side of J6 on the COMET has Pin N corresponding to Pin N+1 on the DB’s J6**

There are also 6 pins that have their *net name* switched from N to P or vice versa which are located in the wiki.

Secondly,
West COMET has IC3 -> J4 and IC3 -> J6 which connect to the DB's J1. 
East COMET has IC3 -> J4 and IC3 -> J6 which connect to the DB's J2.
The important thing to know is that the J2 **is shifted two pins down** from J1.

So West J1-10 corresponds to East J2-8. Note that J1 and J2 are identical otherwise. 

Thirdly,

A quick inspection shows a discrepancy:
COMET J6-56 goes to DB J6-55, but the name goes from COMET 19-P to DB 21-N.
COMET J6-74 goes to DB J6-73, but the name goes from COMET 21-P to DB 19-N.
The nets have been swapped or something wacky is going on.

**Comment by yipengsun** [comment]
It is worth nothing that the J6 pin swapping scheme also applies to J4, after all. But because of the more regular pin out of J4, the result remains unchanged.

**Comment by yipengsun** [comment]
I have also updated this pin swapping scheme in the wiki.

**Comment by yipengsun** [comment]
@nhirsh and @bflaggs have done a great job in manual tracking. So far no violation has been found. (Ignore the ones that go to RJ45 connectors, they don't go to pathfinder).
